site_name: Yantra Launcher Wiki
site_description: 'Documentation for using Yantra Launcher'
site_author: 'The Yantra Launcher Community'
docs_dir: web/
repo_name: 'coderGtm/yantra-app-launcher'
repo_url: 'https://github.com/coderGtm/yantra-app-launcher'
edit_uri: 'edit/main/docs/'
nav:
    - Home: docs/index.md
    - Quickstart: docs/quickstart.md
    - Commands Overview: docs/commands-overview.md
    - Commands:
        - launch: docs/commands/launch.md
        - help: docs/commands/help.md
        - username: docs/commands/username.md
        - alias: docs/commands/alias.md
        - call: docs/commands/call.md
        - search: docs/commands/search.md
        - ai: docs/commands/ai.md
        - theme: docs/commands/theme.md
        - quote: docs/commands/quote.md
        - internet: docs/commands/internet.md
        - web: docs/commands/web.md
        - tts: docs/commands/tts.md
        - bored: docs/commands/bored.md
        - text: docs/commands/text.md
        - reset: docs/commands/reset.md
        - exit: docs/commands/exit.md
    - Frequently Asked Questions: docs/faq.md
    
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  favicon: img/favicon.ico
  logo: img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coderGtm/yantra-app-launcher
      name: View on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/YW7hYbPrTh
      name: Official Discord Community
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/YantraLauncher/
      name: Yantra Launcher subreddit

plugins:
  - git-revision-date-localized:
      type: timeago
  - git-committers:
      repository: coderGtm/yantra-app-launcher
      branch: main
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
